PRAGMA foreign_keys = ON;

-- Public seed generated from a private ledger.
-- It contains watchlist data only. Holdings, cost basis, position size,
-- available shares, allocation, and private review logs are excluded.

INSERT INTO markets (name, country, trade_status, note) VALUES ('A股主板-沪市', '中国', '公开观察', '公开关注池范围：A股主板大盘股') ON CONFLICT(name) DO UPDATE SET country=excluded.country, trade_status=excluded.trade_status, note=excluded.note;
INSERT INTO markets (name, country, trade_status, note) VALUES ('A股主板-深市', '中国', '公开观察', '公开关注池范围：A股主板大盘股') ON CONFLICT(name) DO UPDATE SET country=excluded.country, trade_status=excluded.trade_status, note=excluded.note;

INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('AI算力PCB/服务器硬件', '2026-06-17盘中资金重新回流科技硬件，PCB、先进封装、存储芯片、玻璃基板共振；沪电股份、深南电路、鹏鼎控股为主板核心观察', 'AI服务器、高速交换机、AI PC、PCB高端化、先进封装', '多只核心封板或冲高后接近筹码密集区，追高容易冲高回落', '重点关注', '2026-06-17') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('MLCC/被动元件', '2026-06-17 风华高科个股承接强，但MLCC概念资金分化', 'AI服务器、被动元件、消费电子', '概念资金分化，轻仓试错', '观察中', '2026-06-17') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('半导体封测/先进封装', '自动候选宇宙：先进封装', '先进封装', '自动筛选仅看资金强度，仍需盘中确认承接；追高和同向暴露是主要风险', '观察中', '2026-06-22') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('商业航天/航天装备', '自动候选宇宙：商业航天', '商业航天', '自动筛选仅看资金强度，仍需盘中确认承接；追高和同向暴露是主要风险', '观察中', '2026-06-26') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('小金属/锡锌锗', '锡业股份、驰宏锌锗等6月15日强势，和云南锗业相关标的形成资源线联动', '锡、锌、锗、小金属价格弹性、战略资源', '与云南锗业相关标的相关度高，避免同向暴露过高；涨停次日抛压大', '观察中', '2026-06-16') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('玻纤/电子布涨价', '2026-06-17 中国巨石涨停，玻纤制造强势锚', '电子布涨价、玻纤供需', '涨停后不追，等分歧承接', '重点关注', '2026-06-17') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('面板/玻璃基板', '2026-06-17盘中玻璃基板概念持续活跃，京东方A封涨停并带动主板低价大成交方向', '玻璃基封装载板、OLED量产、面板价格', '多数前排已封板，后排追高风险大；只做前排回踩/次日弱转强', '重点关注', '2026-06-17') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;

INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000021', m.id, '深科技', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = 'AI算力PCB/服务器硬件' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000100', m.id, 'TCL科技', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '面板/玻璃基板' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000636', m.id, '风华高科', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = 'MLCC/被动元件' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000725', m.id, '京东方A', 'A股主板-深市', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '面板/玻璃基板' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000960', m.id, '锡业股份', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '小金属/锡锌锗' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000977', m.id, '浪潮信息', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = 'AI算力PCB/服务器硬件' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000988', m.id, '华工科技', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = 'AI算力PCB/服务器硬件' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '002138', m.id, '顺络电子', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = 'MLCC/被动元件' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '002156', m.id, '通富微电', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '半导体封测/先进封装' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '002428', m.id, '云南锗业', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '小金属/锡锌锗' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '002916', m.id, '深南电路', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = 'AI算力PCB/服务器硬件' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '600118', m.id, '中国卫星', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '商业航天/航天装备' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '600176', m.id, '中国巨石', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '玻纤/电子布涨价' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '600497', m.id, '驰宏锌锗', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '小金属/锡锌锗' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '600563', m.id, '法拉电子', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = 'MLCC/被动元件' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '600707', m.id, '彩虹股份', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '面板/玻璃基板' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;

INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：存储/先进封装；成交额87.9亿，5日均额70.8亿，涨跌幅5.99%，振幅6.63%，评分95', '44.08、46.68、47', '跌破44.08且不能收回，或放量冲高回落跌破46.68，视为短线强度失效', '2026-06-30重点关注', '2026-06-22', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000021' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：面板/玻璃基板；成交额119.0亿，5日均额79.5亿，涨跌幅10.10%，振幅6.60%，评分100', '5.02、5.34', '跌破5.02且不能收回，或放量冲高回落跌破5.34，视为短线强度失效', '2026-06-30重点关注', '2026-06-25', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000100' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '2026-06-17盘中涨约3.97%，成交额约99.3亿元，个股承接强；但MLCC概念资金分化，只适合轻仓试错', '68.88、72.20、74.00', '跌破72.20不能收回，或冲高不过74后放量回落', '2026-06-30观察', '2026-06-10', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000636' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '2026-06-17盘中涨停至6.71，封单强，玻璃基板主板核心；今日不排板，作为次日弱转强观察', '6.05、6.54、6.71', '炸板后不能回封，或次日低开跌破6.54，视为封板强度失效', '2026-06-30重点关注', '2026-06-08', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000725' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '6月15日涨停，成交额约52.6亿元，锡资源强势品种', '38.70、40.30、41.42', '高开封不住且跌破40.30，或跌破38.70不能收回', '2026-06-30重点关注', '2026-06-16', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000960' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：AI服务器/算力硬件；成交额73.8亿，5日均额47.7亿，涨跌幅5.82%，振幅8.23%，评分100', '63.75、68.57、69.08', '跌破63.75且不能收回，或放量冲高回落跌破68.57，视为短线强度失效', '2026-06-30重点关注', '2026-06-25', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000977' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：光模块/算力硬件；成交额199.6亿，5日均额126.5亿，涨跌幅10.00%，振幅4.83%，评分95', '169.26、177.03', '跌破169.26且不能收回，或放量冲高回落跌破177.03，视为短线强度失效', '2026-06-30重点关注', '2026-06-29', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000988' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：被动元件/消费电子；成交额55.5亿，5日均额38.9亿，涨跌幅8.60%，振幅7.27%，评分80', '70.7、74.74、75.7', '跌破70.7且不能收回，或放量冲高回落跌破74.74，视为短线强度失效', '2026-06-30观察', '2026-06-29', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '002138' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：先进封装；成交额143.4亿，5日均额105.3亿，涨跌幅4.37%，振幅6.43%，评分95', '67.73、71.25、72.12', '跌破67.73且不能收回，或放量冲高回落跌破71.25，视为短线强度失效', '2026-06-30重点关注', '2026-06-22', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '002156' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：锗/半导体材料；成交额142.0亿，5日均额104.2亿，涨跌幅10.00%，振幅15.26%，评分100', '106.01、123.09', '跌破106.01且不能收回，或放量冲高回落跌破123.09，视为短线强度失效', '2026-06-30重点关注', '2026-06-24', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '002428' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '2026-06-17盘中涨停至444.27，主板高端PCB强势锚；价格高、已封板，今日不追', '405.00、431.33、444.27', '炸板不能回封，或次日低开跌破431.33', '2026-06-30重点关注', '2026-06-17', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '002916' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：商业航天；成交额67.3亿，5日均额37.0亿，涨跌幅10.00%，振幅12.86%，评分95', '68.68、77.77', '跌破68.68且不能收回，或放量冲高回落跌破77.77，视为短线强度失效', '2026-06-30重点关注', '2026-06-26', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600118' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '2026-06-17盘中涨停至54.60，玻纤制造强势锚；今日不排板，只看次日弱转强或首次分歧承接', '49.00、53.63、54.60', '炸板不能回封，或次日跌破53.63', '2026-06-30重点关注', '2026-06-10', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600176' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '6月15日龙虎榜净买入约2.45亿元，和云南锗业形成锗/锌资源联动；更多作为相关方向风向标', '9.57、9.90、10.16', '冲高回落跌破9.90，或跌破9.57不能收回', '2026-06-30观察', '2026-06-16', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600497' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：被动元件/新能源；成交额28.9亿，5日均额20.1亿，涨跌幅10.00%，振幅10.34%，评分90', '161.95、178.76', '跌破161.95且不能收回，或放量冲高回落跌破178.76，视为短线强度失效', '2026-06-30观察', '2026-06-24', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600563' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：玻璃基板/显示面板；成交额48.7亿，5日均额35.5亿，涨跌幅10.00%，振幅10.48%，评分90', '12.34、13.64', '跌破12.34且不能收回，或放量冲高回落跌破13.64，视为短线强度失效', '2026-06-30观察', '2026-06-23', '2026-06-30' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600707' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;

INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:00 +0800', 64.27, 9.1913, 16372523200.0, 'RSSCAST', '{"pre_close":58.86,"open":59.45,"high":64.75,"low":57.6,"volume":2661147,"amplitude_pct":12.1475,"turnover_rate":0.169054}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000021' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:00 +0800', 5.82, 10.0189, 6656399900.0, 'RSSCAST', '{"pre_close":5.29,"open":5.35,"high":5.82,"low":5.33,"volume":11718305,"amplitude_pct":9.2628,"turnover_rate":0.06125}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000100' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:00 +0800', 72.24, -10.0037, 3230760600.0, 'RSSCAST', '{"pre_close":80.27,"open":72.24,"high":72.24,"low":72.24,"volume":447226,"amplitude_pct":0.0,"turnover_rate":0.038653}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000636' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:00 +0800', 8.68, 9.1824, 44556777600.0, 'RSSCAST', '{"pre_close":7.95,"open":8.15,"high":8.75,"low":8.11,"volume":51878997,"amplitude_pct":8.0503,"turnover_rate":0.146687}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000725' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:00 +0800', 42.69, -4.7736, 5399535500.0, 'RSSCAST', '{"pre_close":44.83,"open":44.2,"high":44.38,"low":41.01,"volume":1286574,"amplitude_pct":7.5173000000000005,"turnover_rate":0.078191}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000960' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:00 +0800', 70.0, 6.3507, 7708729000.0, 'RSSCAST', '{"pre_close":65.82,"open":65.21,"high":70.68,"low":64.83,"volume":1118159,"amplitude_pct":8.8879,"turnover_rate":0.07623}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000977' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:00 +0800', 184.61, 4.2818000000000005, 19722408200.0, 'RSSCAST', '{"pre_close":177.03,"open":179,"high":187.66,"low":173.03,"volume":1090497,"amplitude_pct":8.264100000000001,"turnover_rate":0.108509}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000988' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:00 +0800', 73.1, -2.1943, 4400968200.0, 'RSSCAST', '{"pre_close":74.74,"open":75.07,"high":75.4,"low":70.4,"volume":610367,"amplitude_pct":6.6899,"turnover_rate":0.080683}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '002138' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:00 +0800', 75.87, 4.5329, 11510886000.0, 'RSSCAST', '{"pre_close":72.58,"open":71.19,"high":75.97,"low":69.8,"volume":1556991,"amplitude_pct":8.501,"turnover_rate":0.102606}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '002156' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:00 +0800', 120.18, -3.0806, 8884267200.0, 'RSSCAST', '{"pre_close":124,"open":120,"high":123.38,"low":113.61,"volume":751276,"amplitude_pct":7.879,"turnover_rate":0.115044}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '002428' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:00 +0800', 457.9, 5.468, 6145301800.0, 'RSSCAST', '{"pre_close":434.16,"open":430.46,"high":469.99,"low":425.87,"volume":135452,"amplitude_pct":10.1622,"turnover_rate":0.020375}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '002916' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:02 +0800', 82.05, 1.2713, 6296589200.0, 'RSSCAST', '{"pre_close":81.02,"open":82,"high":84.17,"low":80.75,"volume":764893,"amplitude_pct":4.2212,"turnover_rate":0.064685}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600118' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:00 +0800', 72.88, 2.6768, 15990560100.0, 'RSSCAST', '{"pre_close":70.98,"open":68.5,"high":76.99,"low":68.01,"volume":2218754,"amplitude_pct":12.651499999999999,"turnover_rate":0.055425}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600176' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:02 +0800', 12.11, -5.3906, 4171506700.0, 'RSSCAST', '{"pre_close":12.8,"open":12.42,"high":12.5,"low":11.65,"volume":3457197,"amplitude_pct":6.640600000000001,"turnover_rate":0.06859}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600497' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:00 +0800', 190.8, 0.7392, 2500995700.0, 'RSSCAST', '{"pre_close":189.4,"open":186,"high":195.68,"low":184.1,"volume":131285,"amplitude_pct":6.114,"turnover_rate":0.058349}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600563' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-06-30 15:00:04 +0800', 16.89, 10.0326, 3422619100.0, 'RSSCAST', '{"pre_close":15.35,"open":15.05,"high":16.89,"low":14.69,"volume":2117757,"amplitude_pct":14.3322,"turnover_rate":0.059029}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600707' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
