PRAGMA foreign_keys = ON;

-- Public seed generated from a private ledger.
-- It contains watchlist data only. Holdings, cost basis, position size,
-- available shares, allocation, and private review logs are excluded.

INSERT INTO markets (name, country, trade_status, note) VALUES ('A股主板-沪市', '中国', '公开观察', '公开关注池范围：A股主板大盘股') ON CONFLICT(name) DO UPDATE SET country=excluded.country, trade_status=excluded.trade_status, note=excluded.note;
INSERT INTO markets (name, country, trade_status, note) VALUES ('A股主板-深市', '中国', '公开观察', '公开关注池范围：A股主板大盘股') ON CONFLICT(name) DO UPDATE SET country=excluded.country, trade_status=excluded.trade_status, note=excluded.note;

INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('AI算力PCB/服务器硬件', '2026-06-17盘中资金重新回流科技硬件，PCB、先进封装、存储芯片、玻璃基板共振；沪电股份、深南电路、鹏鼎控股为主板核心观察', 'AI服务器、高速交换机、AI PC、PCB高端化、先进封装', '多只核心封板或冲高后接近筹码密集区，追高容易冲高回落', '重点关注', '2026-06-17') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('半导体封测/先进封装', '自动候选宇宙：先进封装', '先进封装', '自动筛选仅看资金强度，仍需盘中确认承接；追高和同向暴露是主要风险', '观察中', '2026-07-07') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('商业航天/航天装备', '自动候选宇宙：商业航天', '商业航天', '自动筛选仅看资金强度，仍需盘中确认承接；追高和同向暴露是主要风险', '观察中', '2026-06-26') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('小金属/锡锌锗', '锡业股份、驰宏锌锗等6月15日强势，和云南锗业相关标的形成资源线联动', '锡、锌、锗、小金属价格弹性、战略资源', '与云南锗业相关标的相关度高，避免同向暴露过高；涨停次日抛压大', '观察中', '2026-06-16') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('铜/工业金属资源', '自动候选宇宙：铜金资源', '铜金资源', '自动筛选仅看资金强度，仍需盘中确认承接；追高和同向暴露是主要风险', '观察中', '2026-07-02') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('面板/玻璃基板', '2026-06-17盘中玻璃基板概念持续活跃，京东方A封涨停并带动主板低价大成交方向', '玻璃基封装载板、OLED量产、面板价格', '多数前排已封板，后排追高风险大；只做前排回踩/次日弱转强', '重点关注', '2026-06-17') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('黄金/贵金属', '自动候选宇宙：黄金/避险', '黄金/避险', '自动筛选仅看资金强度，仍需盘中确认承接；追高和同向暴露是主要风险', '观察中', '2026-07-02') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;

INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000021', m.id, '深科技', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = 'AI算力PCB/服务器硬件' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000100', m.id, 'TCL科技', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '面板/玻璃基板' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000725', m.id, '京东方A', 'A股主板-深市', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '面板/玻璃基板' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000977', m.id, '浪潮信息', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = 'AI算力PCB/服务器硬件' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '002156', m.id, '通富微电', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '半导体封测/先进封装' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '600118', m.id, '中国卫星', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '商业航天/航天装备' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '600489', m.id, '中金黄金', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '黄金/贵金属' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '600497', m.id, '驰宏锌锗', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '小金属/锡锌锗' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '600707', m.id, '彩虹股份', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '面板/玻璃基板' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '601138', m.id, '工业富联', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = 'AI算力PCB/服务器硬件' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '601899', m.id, '紫金矿业', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '铜/工业金属资源' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;

INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：存储/先进封装；成交额87.9亿，5日均额70.8亿，涨跌幅5.99%，振幅6.63%，评分95', '44.08、46.68、47', '跌破44.08且不能收回，或放量冲高回落跌破46.68，视为短线强度失效', '2026-07-08重点关注', '2026-06-22', '2026-07-08' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000021' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：面板/玻璃基板；成交额119.0亿，5日均额79.5亿，涨跌幅10.10%，振幅6.60%，评分100', '5.02、5.34', '跌破5.02且不能收回，或放量冲高回落跌破5.34，视为短线强度失效', '2026-07-08重点关注', '2026-06-25', '2026-07-08' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000100' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '2026-06-17盘中涨停至6.71，封单强，玻璃基板主板核心；今日不排板，作为次日弱转强观察', '6.05、6.54、6.71', '炸板后不能回封，或次日低开跌破6.54，视为封板强度失效', '2026-07-08观察', '2026-06-08', '2026-07-08' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000725' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：AI服务器/算力硬件；成交额73.8亿，5日均额47.7亿，涨跌幅5.82%，振幅8.23%，评分100', '63.75、68.57、69.08', '跌破63.75且不能收回，或放量冲高回落跌破68.57，视为短线强度失效', '2026-07-08观察', '2026-06-25', '2026-07-08' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000977' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：先进封装；成交额85.8亿，5日均额88.3亿，涨跌幅3.07%，振幅8.76%，评分65', '64、68.21、69.8', '跌破64且不能收回，或放量冲高回落跌破68.21，视为短线强度失效', '2026-07-08重点关注', '2026-07-07', '2026-07-08' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '002156' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：商业航天；成交额67.3亿，5日均额37.0亿，涨跌幅10.00%，振幅12.86%，评分95', '68.68、77.77', '跌破68.68且不能收回，或放量冲高回落跌破77.77，视为短线强度失效', '2026-07-08观察', '2026-06-26', '2026-07-08' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600118' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：黄金/避险；成交额29.0亿，5日均额18.0亿，涨跌幅6.29%，振幅5.46%，评分75', '18.3、19.09、19.28', '跌破18.3且不能收回，或放量冲高回落跌破19.09，视为短线强度失效', '2026-07-08低频观察', '2026-07-02', '2026-07-08' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600489' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '6月15日龙虎榜净买入约2.45亿元，和云南锗业形成锗/锌资源联动；更多作为相关方向风向标', '9.57、9.90、10.16', '冲高回落跌破9.90，或跌破9.57不能收回', '2026-07-08剔除候选', '2026-06-16', '2026-07-08' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600497' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：玻璃基板/显示面板；成交额48.7亿，5日均额35.5亿，涨跌幅10.00%，振幅10.48%，评分90', '12.34、13.64', '跌破12.34且不能收回，或放量冲高回落跌破13.64，视为短线强度失效', '2026-07-08剔除候选', '2026-06-23', '2026-07-08' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600707' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：AI服务器/算力硬件；成交额118.9亿，5日均额93.9亿，涨跌幅3.50%，振幅5.10%，评分65', '64.32、66.01、67.57', '跌破64.32且不能收回，或放量冲高回落跌破66.01，视为短线强度失效', '2026-07-08观察', '2026-07-08', '2026-07-08' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '601138' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：铜金资源；成交额133.0亿，5日均额93.4亿，涨跌幅4.74%，振幅5.73%，评分65', '25.52、26.3、26.96', '跌破25.52且不能收回，或放量冲高回落跌破26.3，视为短线强度失效', '2026-07-08观察', '2026-07-02', '2026-07-08' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '601899' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;

INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-07-08 15:00:00 +0800', 51.13, -5.4374, 8436490400.0, 'RSSCAST', '{"pre_close":54.07,"open":54.1,"high":55,"low":49.33,"volume":1630632,"amplitude_pct":10.4864,"turnover_rate":0.103588}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000021' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-07-08 15:00:00 +0800', 5.04, -4.1825, 5924376600.0, 'RSSCAST', '{"pre_close":5.26,"open":5.19,"high":5.31,"low":4.93,"volume":11724135,"amplitude_pct":7.2243,"turnover_rate":0.06128}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000100' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-07-08 15:00:00 +0800', 7.63, 0.6596000000000001, 25344613400.0, 'RSSCAST', '{"pre_close":7.58,"open":7.69,"high":7.9,"low":7.26,"volume":33222878,"amplitude_pct":8.443299999999999,"turnover_rate":0.093937}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000725' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-07-08 15:00:00 +0800', 78.17, 10.005600000000001, 3193011100.0, 'RSSCAST', '{"pre_close":71.06,"open":78.17,"high":78.17,"low":78.17,"volume":408470,"amplitude_pct":0.0,"turnover_rate":0.027847}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000977' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-07-08 15:00:00 +0800', 65.61, -3.8118, 7529981500.0, 'RSSCAST', '{"pre_close":68.21,"open":67.7,"high":68.8,"low":62.42,"volume":1144668,"amplitude_pct":9.353499999999999,"turnover_rate":0.075434}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '002156' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-07-08 15:00:00 +0800', 77.93, -1.9502, 3052513000.0, 'RSSCAST', '{"pre_close":79.48,"open":79.4,"high":81.83,"low":76.85,"volume":387254,"amplitude_pct":6.265700000000001,"turnover_rate":0.032749}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600118' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-07-08 15:00:02 +0800', 19.88, 0.6582, 1570355300.0, 'RSSCAST', '{"pre_close":19.75,"open":19.41,"high":20.45,"low":19.28,"volume":788957,"amplitude_pct":5.9241,"turnover_rate":0.016276}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600489' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-07-08 15:00:02 +0800', 9.6, -7.156700000000001, 2093945100.0, 'RSSCAST', '{"pre_close":10.34,"open":10.33,"high":10.4,"low":9.58,"volume":2116848,"amplitude_pct":7.9304,"turnover_rate":0.041998}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600497' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-07-08 15:00:02 +0800', 12.26, -5.328200000000001, 2595502300.0, 'RSSCAST', '{"pre_close":12.95,"open":12.95,"high":13.18,"low":11.97,"volume":2088536,"amplitude_pct":9.3436,"turnover_rate":0.058214}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600707' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-07-08 15:00:00 +0800', 66.01, 3.4964000000000004, 11892708800.0, 'RSSCAST', '{"pre_close":63.78,"open":65,"high":67.57,"low":64.32,"volume":1803771,"amplitude_pct":5.0956,"turnover_rate":0.00909}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '601138' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-07-08 15:00:02 +0800', 27.36, -0.9412999999999999, 5419862400.0, 'RSSCAST', '{"pre_close":27.62,"open":27.12,"high":28.03,"low":26.8,"volume":1969818,"amplitude_pct":4.4533000000000005,"turnover_rate":0.009561}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '601899' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
