PRAGMA foreign_keys = ON;

-- Public seed generated from a private ledger.
-- It contains watchlist data only. Holdings, cost basis, position size,
-- available shares, allocation, and private review logs are excluded.

INSERT INTO markets (name, country, trade_status, note) VALUES ('A股主板-沪市', '中国', '公开观察', '公开关注池范围：A股主板大盘股') ON CONFLICT(name) DO UPDATE SET country=excluded.country, trade_status=excluded.trade_status, note=excluded.note;
INSERT INTO markets (name, country, trade_status, note) VALUES ('A股主板-深市', '中国', '公开观察', '公开关注池范围：A股主板大盘股') ON CONFLICT(name) DO UPDATE SET country=excluded.country, trade_status=excluded.trade_status, note=excluded.note;

INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('AI算力PCB/服务器硬件', '2026-06-17盘中资金重新回流科技硬件，PCB、先进封装、存储芯片、玻璃基板共振；沪电股份、深南电路、鹏鼎控股为主板核心观察', 'AI服务器、高速交换机、AI PC、PCB高端化、先进封装', '多只核心封板或冲高后接近筹码密集区，追高容易冲高回落', '重点关注', '2026-06-17') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('半导体封测/先进封装', '自动候选宇宙：先进封装', '先进封装', '自动筛选仅看资金强度，仍需盘中确认承接；追高和同向暴露是主要风险', '观察中', '2026-08-04') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('商业航天/航天装备', '自动候选宇宙：商业航天', '商业航天', '自动筛选仅看资金强度，仍需盘中确认承接；追高和同向暴露是主要风险', '观察中', '2026-09-08') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('小金属/锡锌锗', '自动候选宇宙：锗/半导体材料', '锗/半导体材料', '自动筛选仅看资金强度，仍需盘中确认承接；追高和同向暴露是主要风险', '观察中', '2026-07-21') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('有色铝/周期资源', '自动候选宇宙：铝/周期资源', '铝/周期资源', '自动筛选仅看资金强度，仍需盘中确认承接；追高和同向暴露是主要风险', '观察中', '2026-07-10') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('稀土资源/稀土永磁', '自动候选宇宙：稀土资源', '稀土资源', '自动筛选仅看资金强度，仍需盘中确认承接；追高和同向暴露是主要风险', '观察中', '2026-08-04') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('铜/工业金属资源', '自动候选宇宙：铜金资源', '铜金资源', '自动筛选仅看资金强度，仍需盘中确认承接；追高和同向暴露是主要风险', '观察中', '2026-07-02') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO sectors (name, focus_reason, catalysts, risks, status, updated_on) VALUES ('黄金/贵金属', '自动候选宇宙：黄金/避险', '黄金/避险', '自动筛选仅看资金强度，仍需盘中确认承接；追高和同向暴露是主要风险', '观察中', '2026-07-02') ON CONFLICT(name) DO UPDATE SET focus_reason=excluded.focus_reason, catalysts=excluded.catalysts, risks=excluded.risks, status=excluded.status, updated_on=excluded.updated_on;

INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000021', m.id, '深科技', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = 'AI算力PCB/服务器硬件' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000807', m.id, '云铝股份', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '有色铝/周期资源' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000831', m.id, '中国稀土', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '稀土资源/稀土永磁' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000977', m.id, '浪潮信息', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = 'AI算力PCB/服务器硬件' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '000988', m.id, '华工科技', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = 'AI算力PCB/服务器硬件' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '002156', m.id, '通富微电', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '半导体封测/先进封装' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '002428', m.id, '云南锗业', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '小金属/锡锌锗' WHERE m.name = 'A股主板-深市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '600489', m.id, '中金黄金', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '黄金/贵金属' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '600547', m.id, '山东黄金', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '黄金/贵金属' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '600549', m.id, '厦门钨业', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '稀土资源/稀土永磁' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '600893', m.id, '航发动力', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '商业航天/航天装备' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '600988', m.id, '赤峰黄金', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '黄金/贵金属' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '601138', m.id, '工业富联', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = 'AI算力PCB/服务器硬件' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;
INSERT INTO stocks (code, market_id, name, board, sector_id, is_watchlisted, is_holding, note) SELECT '601899', m.id, '紫金矿业', '主板', se.id, 1, 0, '公开关注池' FROM markets m LEFT JOIN sectors se ON se.name = '铜/工业金属资源' WHERE m.name = 'A股主板-沪市' ON CONFLICT(code, market_id) DO UPDATE SET sector_id=excluded.sector_id, is_watchlisted=1, is_holding=0, name=excluded.name, board=excluded.board, note=excluded.note;

INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：存储/先进封装；成交额65.8亿，5日均额72.1亿，涨跌幅9.99%，振幅19.44%，评分75', '31.82、38.65', '跌破31.82且不能收回，或放量冲高回落跌破38.65，视为短线强度失效', '2026-09-15低频观察', '2026-07-21', '2026-09-15' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000021' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：铝/周期资源；成交额26.6亿，5日均额18.9亿，涨跌幅5.76%，振幅7.49%，评分70', '22、23.15、23.64', '跌破22且不能收回，或放量冲高回落跌破23.15，视为短线强度失效', '2026-09-15剔除候选', '2026-07-10', '2026-09-15' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000807' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：稀土资源；成交额33.9亿，5日均额19.1亿，涨跌幅10.00%，振幅10.94%，评分100', '51.5、57.19', '跌破51.5且不能收回，或放量冲高回落跌破57.19，视为短线强度失效', '2026-09-15观察', '2026-08-07', '2026-09-15' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000831' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：AI服务器/算力硬件；成交额73.8亿，5日均额47.7亿，涨跌幅5.82%，振幅8.23%，评分100', '63.75、68.57、69.08', '跌破63.75且不能收回，或放量冲高回落跌破68.57，视为短线强度失效', '2026-09-15低频观察', '2026-06-25', '2026-09-15' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000977' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：光模块/算力硬件；成交额105.5亿，5日均额86.4亿，涨跌幅6.89%，振幅17.83%，评分85', '95.27、113.15、114.15', '跌破95.27且不能收回，或放量冲高回落跌破113.15，视为短线强度失效', '2026-09-15观察', '2026-07-21', '2026-09-15' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000988' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：先进封装；成交额77.0亿，5日均额97.3亿，涨跌幅8.30%，振幅8.32%，评分65', '51.66、55.6、55.93', '跌破51.66且不能收回，或放量冲高回落跌破55.6，视为短线强度失效', '2026-09-15观察', '2026-08-04', '2026-09-15' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '002156' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：锗/半导体材料；成交额52.8亿，5日均额40.5亿，涨跌幅9.52%，振幅19.51%，评分85', '60.8、73.98', '跌破60.8且不能收回，或放量冲高回落跌破73.98，视为短线强度失效', '2026-09-15观察', '2026-07-21', '2026-09-15' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '002428' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：黄金/避险；成交额29.0亿，5日均额18.0亿，涨跌幅6.29%，振幅5.46%，评分75', '18.3、19.09、19.28', '跌破18.3且不能收回，或放量冲高回落跌破19.09，视为短线强度失效', '2026-09-15低频观察', '2026-07-02', '2026-09-15' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600489' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：黄金/避险；成交额27.7亿，5日均额20.0亿，涨跌幅6.91%，振幅6.94%，评分85', '27.11、28.95、28.99', '跌破27.11且不能收回，或放量冲高回落跌破28.95，视为短线强度失效', '2026-09-15低频观察', '2026-08-05', '2026-09-15' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600547' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：钨/稀土材料；成交额32.1亿，5日均额26.1亿，涨跌幅6.38%，振幅7.04%，评分70', '46.44、49.38、49.71', '跌破46.44且不能收回，或放量冲高回落跌破49.38，视为短线强度失效', '2026-09-15重点关注', '2026-08-04', '2026-09-15' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600549' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：军工装备；成交额23.0亿，5日均额16.0亿，涨跌幅5.82%，振幅7.34%，评分85', '38.7、41.25、41.56', '跌破38.7且不能收回，或放量冲高回落跌破41.25，视为短线强度失效', '2026-09-15低频观察', '2026-09-08', '2026-09-15' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600893' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：黄金/避险；成交额28.5亿，5日均额25.2亿，涨跌幅8.10%，振幅12.99%，评分75', '30.88、34.95、35.08', '跌破30.88且不能收回，或放量冲高回落跌破34.95，视为短线强度失效', '2026-09-15观察', '2026-07-14', '2026-09-15' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600988' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：AI服务器/算力硬件；成交额108.9亿，5日均额81.5亿，涨跌幅7.93%，振幅11.66%，评分85', '55.31、60.98、61.9', '跌破55.31且不能收回，或放量冲高回落跌破60.98，视为短线强度失效', '2026-09-15观察', '2026-07-21', '2026-09-15' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '601138' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;
INSERT INTO watchlist (stock_id, focus_reason, key_levels_text, invalid_condition, status, added_on, updated_on) SELECT st.id, '自动候选：铜金资源；成交额133.0亿，5日均额93.4亿，涨跌幅4.74%，振幅5.73%，评分65', '25.52、26.3、26.96', '跌破25.52且不能收回，或放量冲高回落跌破26.3，视为短线强度失效', '2026-09-15低频观察', '2026-07-02', '2026-09-15' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '601899' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id) DO UPDATE SET focus_reason=excluded.focus_reason, key_levels_text=excluded.key_levels_text, invalid_condition=excluded.invalid_condition, status=excluded.status, updated_on=excluded.updated_on;

INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-09-15 15:10:45 +0800', 33.91, 0.4146, 1712010700.0, 'RSSCAST', '{"pre_close":33.77,"open":33.5,"high":34.65,"low":33.4,"volume":502732,"amplitude_pct":3.7015,"turnover_rate":0.031726}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000021' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-09-15 15:00:00 +0800', 27.06, 0.148, 1195314100.0, 'RSSCAST', '{"pre_close":27.02,"open":27.04,"high":27.27,"low":26.65,"volume":442911,"amplitude_pct":2.2946,"turnover_rate":0.012772}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000807' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-09-15 15:00:00 +0800', 53.16, 1.8196, 1437637900.0, 'RSSCAST', '{"pre_close":52.21,"open":52.25,"high":53.92,"low":51.9,"volume":271250,"amplitude_pct":3.869,"turnover_rate":0.02556}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000831' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-09-15 15:00:00 +0800', 68.76, -0.0872, 2805850300.0, 'RSSCAST', '{"pre_close":68.82,"open":68.42,"high":69.5,"low":68.21,"volume":407172,"amplitude_pct":1.8745,"turnover_rate":0.027757}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000977' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-09-15 15:00:00 +0800', 100.2, 0.2, 3636748100.0, 'RSSCAST', '{"pre_close":100,"open":99.84,"high":102.78,"low":98.33,"volume":362231,"amplitude_pct":4.45,"turnover_rate":0.036043}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '000988' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-09-15 15:00:00 +0800', 57.31, 0.9334, 2422251400.0, 'RSSCAST', '{"pre_close":56.78,"open":56.77,"high":58.58,"low":56.45,"volume":421207,"amplitude_pct":3.7512999999999996,"turnover_rate":0.027758}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '002156' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-09-15 15:00:00 +0800', 90.27, 0.0222, 3508802300.0, 'RSSCAST', '{"pre_close":90.25,"open":90.78,"high":92.95,"low":89.6,"volume":385239,"amplitude_pct":3.7119,"turnover_rate":0.058995}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '002428' AND m.name = 'A股主板-深市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-09-15 15:00:01 +0800', 24.48, -0.4878, 1178825300.0, 'RSSCAST', '{"pre_close":24.6,"open":24.69,"high":24.95,"low":24.37,"volume":478829,"amplitude_pct":2.3577,"turnover_rate":0.009878}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600489' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-09-15 15:00:04 +0800', 34.14, -1.1867, 1366113800.0, 'RSSCAST', '{"pre_close":34.55,"open":34.5,"high":34.78,"low":33.93,"volume":398902,"amplitude_pct":2.4602,"turnover_rate":0.011036}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600547' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-09-15 15:00:02 +0800', 51.14, 3.5642, 3115673600.0, 'RSSCAST', '{"pre_close":49.38,"open":50.37,"high":52.09,"low":50.36,"volume":607214,"amplitude_pct":3.5034,"turnover_rate":0.039076}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600549' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-09-15 15:00:04 +0800', 39.58, -1.4933, 1309498000.0, 'RSSCAST', '{"pre_close":40.18,"open":40.19,"high":40.83,"low":39.5,"volume":326931,"amplitude_pct":3.3101,"turnover_rate":0.012267}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600893' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-09-15 15:00:02 +0800', 43.54, -2.1132999999999997, 1485050900.0, 'RSSCAST', '{"pre_close":44.48,"open":44.48,"high":45,"low":43.13,"volume":337490,"amplitude_pct":4.2041,"turnover_rate":0.020283}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '600988' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-09-15 15:00:02 +0800', 60.8, -1.2506, 3769325500.0, 'RSSCAST', '{"pre_close":61.57,"open":61.25,"high":62.49,"low":60.58,"volume":614209,"amplitude_pct":3.1022000000000003,"turnover_rate":0.003095}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '601138' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
INSERT INTO price_snapshots (stock_id, snapshot_at, price, change_pct, volume_amount, source, note) SELECT st.id, '2026-09-15 15:00:01 +0800', 31.68, -1.7673999999999999, 4146681600.0, 'RSSCAST', '{"pre_close":32.25,"open":32.06,"high":32.2,"low":31.53,"volume":1302033,"amplitude_pct":2.0774999999999997,"turnover_rate":0.00632}' FROM stocks st JOIN markets m ON m.id = st.market_id WHERE st.code = '601899' AND m.name = 'A股主板-沪市' ON CONFLICT(stock_id, snapshot_at, source) DO UPDATE SET price=excluded.price, change_pct=excluded.change_pct, volume_amount=excluded.volume_amount, note=excluded.note;
